Traceback (most recent call last):
  File "traceback_module.py", line 3, in <module>
    raise Exception('This is an error message')
Exception: This is an error message
